---
title: "COVID-19_Results"
author: "Samyak Gupta"
date: "06/05/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(gtools)
library(rjson)
library(plyr)
require(boot)


my.JSON <- fromJSON(file="https://pomber.github.io/covid19/timeseries.json")
world_json <- lapply(my.JSON, function(x){unlist(x)})
world_df <- rbind.fill(lapply(world_json,function(x) do.call("data.frame",as.list(x))))
world_df <- do.call("rbind", world_json)
world_df <- as.data.frame(world_df)

India_json <- lapply(my.JSON$India, function(x){ unlist(x)})
India_df <- rbind.fill(lapply(India_json,function(x) do.call("data.frame", as.list(x))))
India_df <- do.call("rbind", India_json)
India_df <- as.data.frame(India_df)


I_date <- as.Date(India_df$date,format = "%Y-%m-%d")
I_confirmed <- as.numeric(India_df$confirmed)
I_deaths <- as.numeric(India_df$deaths)
I_recovered <- as.numeric(India_df$recovered)

date <- as.Date(world_df$date,format = "%Y-%m-%d")
confirmed <- as.numeric(world_df$confirmed)
deaths <- as.numeric(world_df$deaths)
recovered <- as.numeric(world_df$recovered)



#No. of days since 22-jan-2020
today = 105


t_case=c();t_dead=c();t_date=c(1:today)
count=0
cols = seq(from=2, length=today,by=4)

for (j in cols){
  total_cases = 0;total_deaths = 0
  count = count + 1
  for(i in world_df[,j]){
    total_cases = total_cases + as.numeric(i)
  }
  for(k in world_df[,j+1]){
    total_deaths = total_deaths + as.numeric(k)
  }
  t_case[count] = as.numeric(total_cases)
  t_dead[count] = as.numeric(total_deaths)
}
t_date <- as.Date(t_date,origin = "2020-01-21")
comp_w_df = cbind(t_date,t_case,t_dead)

comp_w_df <- as.data.frame(comp_w_df)
confirmed_1 <- as.numeric(comp_w_df$t_case)
deaths_1 <- as.numeric(comp_w_df$t_dead)

fit = lm(confirmed_1~poly(t_date,6))
a = today+1; b = today+7
new <- data.frame(t_date = as.Date(a:b ,origin = "2020-01-21"))
predict_date <- as.Date(a:b,origin="2020-01-20")
predict_date = c(as.character.Date(predict_date))
fit4 = lm(I_confirmed~poly(I_date,6))
```

## Predictions and Plots

So this little project is just for us to learn and apply the simple techniques used in statistical learning in a real time problem in the world.

Here we predict two things:
1) No. of confirmed cases for the next few days for the world.
2) No. of confirmed cases for the next few days for India.

```{r pressure, echo=FALSE}
plot(t_date,confirmed_1,pch = 7,xlab = "date",ylab = "confirmed cases",main = "Total Confirmed cases per day")
points(t_date,fitted(fit),col="blue",pch=20)
plot(I_date,I_confirmed,pch = 7,xlab = "date",ylab = "confirmed cases")
points(I_date,fitted(fit4),col="blue",pch=20)
```
```{r echo=FALSE}
abc <- data.frame(I_date = as.Date(a:b ,origin = "2020-01-20"))
Final_2 <- cbind(new,predict.lm(fit4,abc,interval = "confidence"))
Final <- cbind(predict_date,predict.lm(fit,new,interval = "confidence"))
knitr::kable(Final)
knitr::kable(Final_2)
```
